apiVersion: apps/v1
kind: Deployment
metadata:
  name: musify-platform-app
  labels:
    app: musify-platform-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musify-platform-app
  template:
    metadata:
      labels:
        app: musify-platform-app
    spec:
      containers:
      - name: musify-backend
        image: crastenomis/musify-platform-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: musify-env-config
        - secretRef:
            name: musify-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5